export const symptoms = [
    {label: 'blister', id: 'blister'}, 
    {label: 'passage of gases', id: 'passage_of_gases'}, 
    {label: 'dark urine', id: 'dark_urine'}, 
    {label: 'hip joint pain', id: 'hip_joint_pain'}, 
    {label: 'extra marital contacts', id: 'extra_marital_contacts'}, 
    {label: 'increased appetite', id: 'increased_appetite'}, 
    {label: 'enlarged thyroid', id: 'enlarged_thyroid'}, 
    {label: 'muscle weakness', id: 'muscle_weakness'}, 
    {label: 'fast heart rate', id: 'fast_heart_rate'}, 
    {label: 'nausea', id: 'nausea'}, 
    {label: 'loss of appetite', id: 'loss_of_appetite'}, 
    {label: 'loss of smell', id: 'loss_of_smell'}, 
    {label: 'phlegm', id: 'phlegm'}, 
    {label: 'vomiting', id: 'vomiting'}, 
    {label: 'mild fever', id: 'mild_fever'}, 
    {label: 'lethargy', id: 'lethargy'}, 
    {label: 'malaise', id: 'malaise'}, 
    {label: 'internal itching', id: 'internal_itching'}, 
    {label: 'yellowish skin', id: 'yellowish_skin'}, 
    {label: 'knee pain', id: 'knee_pain'}, 
    {label: 'blurred and distorted vision', id: 'blurred_and_distorted_vision'}, 
    {label: 'swollen blood vessels', id: 'swollen_blood_vessels'}, 
    {label: 'chest pain', id: 'chest_pain'}, 
    {label: 'skin rash', id: 'skin_rash'}, 
    {label: 'cramps', id: 'cramps'}, 
    {label: 'weight loss', id: 'weight_loss'}, 
    {label: 'patches in throat', id: 'patches_in_throat'}, 
    {label: 'fatigue', id: 'fatigue'}, 
    {label: 'inflammatory nails', id: 'inflammatory_nails'}, 
    {label: 'blood in sputum', id: 'blood_in_sputum'}, 
    {label: 'sunken eyes', id: 'sunken_eyes'}, 
    {label: 'fluid overload', id: 'fluid_overload'}, 
    {label: 'yellowing of eyes', id: 'yellowing_of_eyes'},
    {label: 'shivering', id: 'shivering'}, 
    {label: 'dizziness', id: 'dizziness'}, 
    {label: 'lack of concentration', id: 'lack_of_concentration'}, 
    {label: 'indigestion', id: 'indigestion'}, 
    {label: 'obesity', id: 'obesity'}, 
    {label: 'coma', id: 'coma'}, 
    {label: 'redness of eyes', id: 'redness_of_eyes'}, 
    {label: 'high fever', id: 'high_fever'}, 
    {label: 'red sore around nose', id: 'red_sore_around_nose'}, 
    {label: 'muscle pain', id: 'muscle_pain'}, 
    {label: 'neck pain', id: 'neck_pain'}, 
    {label: 'joint pain', id: 'joint_pain'},
    {label: 'irritability', id: 'irritability'},
    {label: 'swelling of stomach', id: 'swelling_of_stomach'}, 
    {label: 'mucoid sputum', id: 'mucoid_sputum'},
    {label: 'yellow urine', id: 'yellow_urine'}, 
    {label: 'loss of balance', id: 'loss_of_balance'}, 
    {label: 'swelled lymph nodes', id: 'swelled_lymph_nodes'},
    {label: 'depression', id: 'depression'}, 
    {label: 'swelling joints', id: 'swelling_joints'}, 
    {label: 'spotting  urination', id: 'spotting_ urination'},
    {label: 'spinning movements', id: 'spinning_movements'}, 
    {label: 'stiff neck', id: 'stiff_neck'}, 
    {label: 'acute liver failure', id: 'acute_liver_failure'}, 
    {label: 'cough', id: 'cough'}, 
    {label: 'diarrhoea', id: 'diarrhoea'}, 
    {label: 'dischromic  patches', id: 'dischromic _patches'}, 
    {label: 'pain behind the eyes', id: 'pain_behind_the_eyes'}, 
    {label: 'bladder discomfort', id: 'bladder_discomfort'}, 
    {label: 'blackheads', id: 'blackheads'}, 
    {label: 'sinus pressure', id: 'sinus_pressure'}, 
    {label: 'painful walking', id: 'painful_walking'}, 
    {label: 'weakness in limbs', id: 'weakness_in_limbs'}, 
    {label: 'movement stiffness', id: 'movement_stiffness'}, 
    {label: 'family history', id: 'family_history'}, 
    {label: 'yellow crust ooze', id: 'yellow_crust_ooze'}, 
    {label: 'cold hands and feets', id: 'cold_hands_and_feets'}, 
    {label: 'scurring', id: 'scurring'}, 
    {label: 'runny nose', id: 'runny_nose'}, 
    {label: 'anxiety', id: 'anxiety'}, 
    {label: 'bruising', id: 'bruising'}, 
    {label: 'restlessness', id: 'restlessness'}, 
    {label: 'swollen legs', id: 'swollen_legs'}, 
    {label: 'drying and tingling lips', id: 'drying_and_tingling_lips'},
    {label: 'visual disturbances', id: 'visual_disturbances'}, 
    {label: 'watering from eyes', id: 'watering_from_eyes'}, 
    {label: 'weakness of one body side', id: 'weakness_of_one_body_side'}, 
    {label: 'nodal skin eruptions', id: 'nodal_skin_eruptions'}, 
    {label: 'palpitations', id: 'palpitations'}, 
    {label: 'irregular sugar level', id: 'irregular_sugar_level'},
    {label: 'brittle nails', id: 'brittle_nails'}, 
    {label: 'skin peeling', id: 'skin_peeling'}, 
    {label: 'stomach bleeding', id: 'stomach_bleeding'}, 
    {label: 'bloody stool', id: 'bloody_stool'}, 
    {label: 'ulcers on tongue', id: 'ulcers_on_tongue'}, 
    {label: 'belly pain', id: 'belly_pain'}, 
    {label: 'constipation', id: 'constipation'}, 
    {label: 'burning micturition', id: 'burning_micturition'},
    {label: 'polyuria', id: 'polyuria'},
    {label: 'prominent veins on calf', id: 'prominent_veins_on_calf'}, 
    {label: 'abnormal menstruation', id: 'abnormal_menstruation'}, 
    {label: 'rusty sputum', id: 'rusty_sputum'}, 
    {label: 'abdominal pain', id: 'abdominal_pain'}, 
    {label: 'muscle wasting', id: 'muscle_wasting'}, 
    {label: 'mood swings', id: 'mood_swings'}, 
    {label: 'slurred speech', id: 'slurred_speech'}, 
    {label: 'headache', id: 'headache'}, 
    {label: 'silver like dusting', id: 'silver_like_dusting'},
    {label: 'acidity', id: 'acidity'}, 
    {label: 'receiving unsterile injections', id: 'receiving_unsterile_injections'},
    {label: 'history of alcohol consumption', id: 'history_of_alcohol_consumption'},
    {label: 'throat irritation', id: 'throat_irritation'},
    {label: 'unsteadiness', id: 'unsteadiness'}, 
    {label: 'toxic look (typhos)', id: 'toxic_look_(typhos)'}, 
    {label: 'puffy face and eyes', id: 'puffy_face_and_eyes'}, 
    {label: 'stomach pain', id: 'stomach_pain'},
    {label: 'foul smell of urine', id: 'foul_smell_of urine'}, 
    {label: 'sweating', id: 'sweating'}, 
    {label: 'chills', id: 'chills'}, 
    {label: 'continuous sneezing', id: 'continuous_sneezing'},
    {label: 'dehydration', id: 'dehydration'},
    {label: 'breathlessness', id: 'breathlessness'},
    {label: 'congestion', id: 'congestion'}, 
    {label: 'swollen extremeties', id: 'swollen_extremeties'}, 
    {label: 'pain in anal region', id: 'pain_in_anal_region'}, 
    {label: 'irritation in anus', id: 'irritation_in_anus'},
    {label: 'back pain', id: 'back_pain'}, 
    {label: 'pain during bowel movements', id: 'pain_during_bowel_movements'},
    {label: 'pus filled pimples', id: 'pus_filled_pimples'}, 
    {label: 'excessive hunger', id: 'excessive_hunger'}, {
    label: 'distention of abdomen', id: 'distention_of_abdomen'}, 
    {label: 'altered sensorium', id: 'altered_sensorium'}, 
    {label: 'red spots over body', id: 'red_spots_over_body'}, 
    {label: 'continuous feel of urine', id: 'continuous_feel_of_urine'}, 
    {label: 'weight gain', id: 'weight_gain'}, 
    {label: 'small dents in nails', id: 'small_dents_in_nails'}, 
    {label: 'receiving blood transfusion', id: 'receiving_blood_transfusion'}, 
    {label: 'itching', id: 'itching'}
]